// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppAnnoy.h"
#include <Rcpp.h>

using namespace Rcpp;

// getArchictectureStatus
std::string getArchictectureStatus();
RcppExport SEXP _RcppAnnoy_getArchictectureStatus() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(getArchictectureStatus());
    return rcpp_result_gen;
END_RCPP
}
// annoy_version
Rcpp::IntegerVector annoy_version();
RcppExport SEXP _RcppAnnoy_annoy_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(annoy_version());
    return rcpp_result_gen;
END_RCPP
}
